package com.littleyellow.greendaotest.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.littleyellow.greendaotest.bean.User;
import com.littleyellow.greendaotest.bean.Score;

import com.littleyellow.greendaotest.db.UserDao;
import com.littleyellow.greendaotest.db.ScoreDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig scoreDaoConfig;

    private final UserDao userDao;
    private final ScoreDao scoreDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        scoreDaoConfig = daoConfigMap.get(ScoreDao.class).clone();
        scoreDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        scoreDao = new ScoreDao(scoreDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Score.class, scoreDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        scoreDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ScoreDao getScoreDao() {
        return scoreDao;
    }

}
